package:
  name: openalea.core
  version: 1.4.1

source:
  git_url: https://github.com/openalea/openalea


build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools

test:
  imports:
    - openalea.core

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License