package:
  name: openalea.sconsx
  version: 2.1.0

source:
  git_url: https://github.com/openalea/sconsx
  #path: ../../sconsx

build:
  preserve_egg_dir: True
  number: 1

requirements:
  build:
    - python
    - openalea.deploy #==2.0.0
  run:
    - python
    - scons
    - openalea.deploy

test:
  imports:
    - SCons
    - openalea.sconsx

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-c License
