package:
  name: cgal
  version: 4.6.3

source:
   fn: CGAL-4.6.3.tar.gz
   url: http://gforge.inria.fr/frs/download.php/file/35138/CGAL-4.6.3.tar.gz

about:
  home: http://www.cgal.org/
  license: GPL/LGPL
  summary: robust C++ implementation of geometric algorithms

# needs boost - this is now in defaults.  the ioos boost is broken (and has been
# deprecated but still appears in the channel - 2015-08-02)

requirements:
  # it doesn't really require python, but maybe that will fix
  # the missing bin directory
  build:
   - boost
   - python
   - cmake
   - mpfr [linux]
   - mpfr [osx]
   - m2w64-mpfr [win]
   - gmp  [linux]
   - gmp  [osx]
   - m2w64-gmp [win]
   - qt <5
   - patchelf [linux]
  run:
   - boost
   - gmp  [linux]
   - gmp  [osx]
   - mpfr [linux]
   - mpfr [osx]
   - qt <5

test:
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL.so  # [linux]
    - test -f ${PREFIX}/lib/libCGAL.dylib  # [osx]