package:
  name: openalea.deploy
  version: 2.1.3

source:
  git_url: https://github.com/pradal/deploy
  #git_rev: v2.1.1

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pywin32 # [win]
  run:
    - python
    - setuptools
    - pywin32 # [win]

test:
  imports:
    - openalea.deploy

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License